# --- Basic options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (https://username.github.io) then use these settings:
url: "https://christian-gmeiner.info"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Chaos Computing

# Short description of your site
description: wer kämpft kann verlieren - wer nicht kämpft hat schon verloren

# Your name to show in the footer
author: Christian Gmeiner

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Bugfixing Service: "bugfixing"
  Impressum: "impressum"

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"

# By default, the image is cut into a circle. You can disable this behaviour here.
round-avatar: true

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
#title-img: /path/to/image


# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
social-network-links:
  email: "christian.gmeiner@gmail.com"
  facebook: yourname  # eg. daattali
  github: austriancoder    # eg. daattali
  twitter: yourname   # eg. daattali
  reddit: yourname    # eg. daattali
  google-plus: +christiangmeiner   # eg. +DeanAttali or 109424658772469020925
  linkedin: yourname  # eg. daattali
  xing: yourname      # eg. daattali
  stackoverflow: yourlink  # eg. "3943160/daattali"
  snapchat: yourname  # eg. daattali
  instagram: yourname # eg. daattali
  youtube: yourlink   # eg. user/daattali or channel/daattali
  spotify: yourname   # eg. daattali
  telephone: yourphone   # eg. +14159998888
  steam: yourname     # eg. daattali
  twitch: yourname    # eg. daattali
  yelp: yourname      # eg. daattali

# --- General options --- #

# Select which social network share links to show in posts
share-links-active:
  twitter: false
  facebook: false
  google: false
  linkedin: false

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "christian-gmeiner.info"  # eg. "deanattali.com/beautiful-jekyll"

# Create a "tags" index page and make tags on each post clickable
link-tags: true

# Excerpt Word Length - Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Comments --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# To use Facebook Comments, fill in a Facebook App ID
#fb_comment_id: ""

# To use Staticman comments, fill in "repository", "branch", and "endpoint"
staticman:
  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
  branch     : master # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
  endpoint   : # URL of your own deployment, with a trailing slash (will fallback to a public GitLab instance) eg. https://<your-api>/v3/entry/github/
  reCaptcha:
    # reCaptcha for Staticman (OPTIONAL, but recommended for spam protection)
    # If you use reCaptcha, you must also set these parameters in staticman.yml
    siteKey  : # Use your own site key, you need to apply for one on Google
    secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>

# To use Utterances comments: (1) fill in "repository" (make sure the repository is public), (2) Enable Issues in your repository,
# (3) Install the Utterances app in your repository https://github.com/apps/utterances
# See more details about the parameters below at https://utteranc.es/
utterances:
  repository: # GitHub username/repository eg. "daattali/beautiful-jekyll"
  issue-term: title   # Mapping between blog posts and GitHub issues
  theme: github-light # Utterances theme
  label: blog-comments # Label that will be assigned to GitHub Issues created by Utterances


# --- Misc --- #

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""


# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
